### ISSUE TITLE
Review API surface area for Steeltoe.Management.*

### ISSUE THREAD

**Issue by hananiel** [SteeltoeOSS/Steeltoe#1122]
### 
**Surface API:**

- Seal public types that don't seem (properly) designed for inheritance (please indicate where I'm wrong)
- Replace optional parameters with overloads in publicly exposed methods
- Add input validation (null checks) on the parameters of publicly exposed methods
- Change publicly exposed fields into properties, unless they are constants

**Activate the next Sonar rules:**

- [ ] - [Address SA1401: Fields should be private #928](https://github.com/SteeltoeOSS/Steeltoe/issues/928)
- [ ] - [Address S1168: Empty arrays and collections should be returned instead of null #916](https://github.com/SteeltoeOSS/Steeltoe/issues/916)
- [ ] - [Address S2360: Optional parameters should not be used #929](https://github.com/SteeltoeOSS/Steeltoe/issues/929)
- [ ] - S3900: Arguments of public methods should be validated against null
- [ ] - [Address S3956: "Generic.List" instances should not be part of public APIs #941](https://github.com/SteeltoeOSS/Steeltoe/issues/941)
- [ ] - [Address S4023: Interfaces should not be empty #947](https://github.com/SteeltoeOSS/Steeltoe/issues/947)
- [ ] - [Address S4004: Collection properties should be readonly #946](https://github.com/SteeltoeOSS/Steeltoe/issues/946)

**Comment by bart-vmware** [comment]
Duplicate of #905.
